### ISSUE TITLE
Unable to restore custom object of type _tf_keras_metric currently while loading previously saved model without custom layers

### ISSUE THREAD

**Issue by lsl1229840757** [jakeret/unet#8]
I ran the scripts/oxford_iiit_pet.py and got a saved model in model_path.

now I would like to load this model with:
`model = tf.keras.models.load_model(model_path)`

but I get:

> ValueError: Unable to restore custom object of type _tf_keras_metric currently. Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`.

I searched this question on Stack Overflow and found that it worked when I changed the code to this:
`model = tf.keras.models.load_model(model_path, custom_objects = {"mean_iou": mean_iou, "dice_coefficient": dice_coefficient})`

so, I think in order to deserialize the model more conveniently, these two metrics should subclass `tf.keras.metrics.Metric`

**Comment by jakeret** [comment]
Hi @lsl1229840757, thanks for letting me know.
I'll have a look

**Comment by GraceAdams** [comment]
When I tried to use the same fix, I get 'NameError: name 'mean_iou' is not defined. So I specifically imported metrics from unet, then used this:
`model = tf.keras.models.load_model(model_path, custom_objects = {"mean_iou": metrics.mean_iou, "dice_coefficient": metrics.dice_coefficient})`
Unfortunately I get a new error: ValueError: Unknown metric function:mean_iou
 I'm not using the existing examples, but because I'm using the unet virtual environment I'm confident that the setups are the same.

**Comment by NikosSpanos** [comment]
Why is this question closed? I have a similar issue with HammingLoss metric from TensorFlow Addons. What was the solution that worked?

**Comment by jakeret** [comment]
Hi @NikosSpanos I've merged a PR that was resolving this issue ([here](https://github.com/jakeret/unet/pull/12/files#diff-2fbe9edc8f2c62fe3cf45e094a5ac9d1e43b333b49b798811fa162a74f3dbf7eR64))

Essentially it requires to pass a dict with the custom object when loading the model

**Comment by NikosSpanos** [comment]
@jakeret  ty for the response. Indeed custom objects could have been a solution. Although didn't work in my case since I use Hamming Loss from Tensorflo Addons ([here](https://www.tensorflow.org/addons/api_docs/python/tfa/metrics/HammingLoss)). However, the trick for me was to set the ```compile=``` argument to False and then re-compile the model after the load. Maybe this approach will help others in the future when using metrics from the TensorFlow Addon hub.

**Comment by lspinheiro** [comment]
@NikosSpanos  Won't setting `compile=False`  reset the state of the model? In my case, I'm trying to reload the model and recover the state of the optimizer, and loading the model fails for a similar issue. I don't think re-compiling is a suitable solution if you need more than the model weights.
